name: Selenium Tests with JUnit 5

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up JDK (Java 20 for your project)
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Using Adoptium (Temurin) JDK
        version: '20'
    
    # Step 3: Set up Maven
    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        version: '20'
    
    # Step 4: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 5: Build the project with Maven
    - name: Build with Maven
      run: mvn clean install -DskipTests

    # Step 6: Run the tests
    - name: Run Selenium Tests
      run: mvn test
