name: Run Selenium WebDriver Tests with JUnit 5

on:
  push:
    branches:
      - main  # Or the default branch you use
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use 'windows-latest' or 'macos-latest' based on your preference
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK (Java 20 for your project)
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'adoptopenjdk'

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Install dependencies with Maven
    - name: Build with Maven
      run: mvn clean install -DskipTests

    # Step 5: Run the tests
    - name: Run tests
      run: mvn test

    # Optional: Generate Allure report after tests are run
    - name: Generate Allure report
      run: mvn allure:serve
